# https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml

# Default state for all rules
default: true

# MD013/line-length : Line length : https://github.com/DavidAnson/markdownlint/blob/v0.39.0/doc/md013.md
MD013:
  # Number of characters
  line_length: 120

MD033:
  # Allowed elements
  allowed_elements: ["br", "details", "summary"]

MD041: false
# first-line-heading/
