command_case = "lower_case" # or "upper_case"
enable_external_cmake_lint = true # true to use external cmake-lint
line_max_words = 140

[format]
program = "gersemi"
# Use two space indentation.
args = ["--indent", "2"]
